# Generated by Django 4.1.3 on 2022-11-15 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField(verbose_name='Event Date')),
                ('category', models.CharField(choices=[('B', 'Business Meeting'), ('U', 'UXDI'), ('S', 'Software Engineer'), ('D', 'Designer'), ('F', 'Finance'), ('R', 'Real Estate'), ('I', 'Self-Improvement'), ('M', 'Marketing')], default='B', max_length=1)),
            ],
        ),
    ]
