# Generated by Django 4.1.3 on 2022-11-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('B', 'Business Meeting'), ('U', 'UXDI'), ('S', 'Software Engineer'), ('D', 'Designer'), ('F', 'Finance'), ('R', 'Real Estate'), ('I', 'Self-Improvement'), ('M', 'Marketing')], default='B', max_length=1),
        ),
    ]
